name: Build Android

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ANDROID_SDK_ROOT: /usr/local/lib/android/sdk

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle

      - name: Install Android SDK (cmdline-tools, platform-tools, build-tools)
        run: |
          sudo mkdir -p "$ANDROID_SDK_ROOT"
          sudo chown "$USER:$USER" "$ANDROID_SDK_ROOT"
          curl -fsSL -o cmdtools.zip https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
          unzip -q cmdtools.zip -d "$ANDROID_SDK_ROOT"
          mv "$ANDROID_SDK_ROOT/cmdline-tools" "$ANDROID_SDK_ROOT/cmdline-tools-tmp"
          mkdir -p "$ANDROID_SDK_ROOT/cmdline-tools/latest"
          mv "$ANDROID_SDK_ROOT/cmdline-tools-tmp/"* "$ANDROID_SDK_ROOT/cmdline-tools/latest/"
          yes | "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager" --licenses
          "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager" \
            "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      - name: Create local.properties
        run: echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build (assembleDebug)
        run: ./gradlew --no-daemon --stacktrace assembleDebug

      - name: Upload artifacts (APK/AAB + logs)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: android-artifacts
          if-no-files-found: warn
          path: |
            **/build/outputs/**/*.apk
            **/build/outputs/**/*.aab
            **/build/reports/**
            ~/.gradle/daemon/*/*.log
            ~/.gradle/build-scan-data/**
