name: Build Android

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ANDROID_SDK_ROOT: /usr/local/lib/android/sdk
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle

      - name: Point to preinstalled Android SDK
        run: echo "sdk.dir=/usr/local/lib/android/sdk" > local.properties

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build (assembleDebug)
        run: ./gradlew --no-daemon --stacktrace assembleDebug

      - name: Upload build artifacts (APK/AAB)
        uses: actions/upload-artifact@v4
        with:
          name: android-artifacts
          if-no-files-found: warn
          path: |
            **/build/outputs/**/*.apk
            **/build/outputs/**/*.aab
