name: Build Android

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ANDROID_SDK_ROOT: /usr/local/lib/android/sdk
      XDG_CONFIG_HOME: /home/runner

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle

      - name: Install Android SDK (platform 34, build-tools 34.0.0, aapt2)
        run: |
          yes | "${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager" \
            "platform-tools" "platforms;android-34" "build-tools;34.0.0" || true
          # Symlink aapt2 so Gradle can find it in /usr/bin
          ln -sf ${ANDROID_SDK_ROOT}/build-tools/34.0.0/aapt2 /usr/bin/aapt2

      - name: Create local.properties
        run: echo "sdk.dir=${ANDROID_SDK_ROOT}" > local.properties

      - name: Prepare debug keystore
        run: |
          set -euxo pipefail
          mkdir -p ~/.android
          if [ ! -f ~/.android/debug.keystore ]; then
            keytool -genkeypair \
              -alias androiddebugkey \
              -keypass android \
              -keystore ~/.android/debug.keystore \
              -storepass android \
              -dname "CN=Android Debug,O=Android,C=US" \
              -keyalg RSA -keysize 2048 -validity 10000
          fi
          mkdir -p ~/.config/.android
          ln -sf ~/.android/debug.keystore ~/.config/.android/debug.keystore

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build (assembleDebug)
        run: ./gradlew --no-daemon --stacktrace assembleDebug

      - name: Upload artifacts (APK/AAB + logs)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: android-artifacts
          if-no-files-found: warn
          path: |
            **/build/outputs/**/*.apk
            **/build/outputs/**/*.aab
            **/build/reports/**
            **/build/test-results/**
            ~/.gradle/daemon/*/daemon-*.log
            ~/.gradle/build-scan-data/**
